### ISSUE TITLE
Proposal: Exemplars

### ISSUE THREAD

**Issue by cnnradams** [open-telemetry/oteps#112]
This proposal defines exemplars within OpenTelemetry and specifies behaviour for exemplars for the default set of aggregations: [Proposal doc](https://docs.google.com/document/d/1XpSCxzt5Q7pAIv6EeNt5x4jbqYO6pERVBO02sJvvMws/edit?ts=5ed6bf8e)

**Comment by MrAlias** [comment]
From Gitter: the plan is to replace this with a PR containing the proposal.
