### ISSUE TITLE
Proposal: Establish consistent guidelines for organizing vendor specific contributions to the OpenTelemetry Collector

### ISSUE THREAD

**Issue by alolita** [open-telemetry/oteps#141]
Today, some vendor contributed components are being accepted into the OpenTelemetry Collector repositories. Other vendor contributions are being rejected. There are no consistent rules for merging vendor specific code in the OpenTelemetry Collector repositories.
 
I propose that all vendor specific components for the Collector reside in the “github.com/open-telemetry/opentelemetry-collector-contrib” repository. This will facilitate static linking of all Go components needed by the user. 
The alternative is that vendor components reside in vendor-hosted repositories which will lead to fragmentation of the Collector.

In particular, I request that the AWS authentication contribution supporting AWS SIGv4 for Collector based exporters reside in the github.com/open-telemetry/opentelemetry-collector-contrib repository. This would provide users with an easy-to-access, single source for all OpenTelemetry Collector components. In addition, it enables users to easily build exporters with statically linked SIGv4 support. 

AWS will continue to maintain its component and create PRs against the collector-contrib repo for all revisions. We will work toward achieving collector-contrib maintainer status and then be able to manage code reviews and handle merging PRs appropriately. In the meantime, we will continue to submit PRs to be reviewed and merged into the collector-contrib repo by the current maintainers.

cc: Collector maintainers @bogdandrutu @tigrannajaryan

**Comment by tigrannajaryan** [comment]
>I propose that all vendor specific components for the Collector reside in the “github.com/open-telemetry/opentelemetry-collector-contrib” repository. 

This is already our policy today. However, rejections of vendor-specific proposals are still possible on the technical merit of the contributions (low quality code, poor test coverage, etc) or because the contributions are not aligned with Collector vision and roadmap.

I think it will be useful to have a document that makes this abundantly clear.

**Comment by trask** [comment]
Closing, if there's still a need for this, probably better to open in collector repo(s) or maybe community repo
