### ISSUE TITLE
Proposal: Reduce clock-skew issues in mobile and other client-side trace sources

### ISSUE THREAD

**Issue by bryce-b** [open-telemetry/oteps#154]
I'm creating this ticket per discussion in the OpenTelemetry maintainers' meeting 05/10/2021

Clock-skew will always be a problem with distributed tracing, but the degree of skew that occurs on unmanaged devices (by 'unmanaged' I mean devices outside of the software provider's control) is untenable. 

<img width="1843" alt="Screen Shot 2021-04-26 at 10 44 06 AM" src="https://user-images.githubusercontent.com/75274611/117861090-e5a1b600-b245-11eb-928d-d3ecad1a4247.png">

This screenshot shows the degree of clock skew between a mobile device and a backend server while tracing a synchronous request. The mobile device is using an automatically sync'd system clock, but the degree of skew could be much, much worst, as the clock can be set at the whim of the mobile phone's owner (think days, months, years of skew).

I'd like to brainstorm some solutions to this problem.
Some possible solutions could be:
- client side monitors should operate in offset times that can be later set relative to some time authority (collector?)
- client side could sync to a non-system time authority
- distributed traces could be processed to re-align spans based off relation (if a http request is made to a backend service they should probably overlap to some degree)

**Comment by iNikem** [comment]
> it may be enough to send the "current" time with each request, so the receiver can calculate the offset between the current time of the sender and it's own current time.

This is more or less what we did in Plumbr

**Comment by ivomagi** [comment]
There is a blogpost, exposing conceptually how the clock skew was handled back in the days: https://plumbr.io/blog/monitoring/time-in-distributed-systems

**Comment by t2t2** [comment]
In case this issue gets active once again, archive.org link for above blog post:
https://web.archive.org/web/20210123103641/https://plumbr.io/blog/monitoring/time-in-distributed-systems

**Comment by trask** [comment]
Closing as stale. If there's still interest, please re-open in the specification repo as we are planning to archive this repo.
