### ISSUE TITLE
Rename the repo to "otrfcs"?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/oteps#2]

**Comment by iredelmeier** [comment]
For more context, there have been similar discussions for other repos with "common" names, e.g., in [community](https://github.com/open-telemetry/community/issues/12) and in [opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/2).

For RFCs specifically, we could also do something like rename them from RFCs to OTEPs (for "OpenTelemetry Enhancement Proposal"), à la Python's PEPs and Kubernetes's KEPs. Thoughts?

**Comment by bogdandrutu** [comment]
RFCs sounds like standards and I know there is a push from CNCF to not define standards. If we scope the rfc to OpenTelemetry should be fine that's the main reason.

**Comment by ernado** [comment]
Please do, collisions with IETF RFC are unnecessary.

Sadly, Rust has already done this:
https://github.com/rust-lang/rfcs

Currently, RFC 1234 is unambiguously referring to IETF (with expection to Rust), let's not make it more complicated.

**Comment by bogdandrutu** [comment]
Based on the comments I think "oteps" is better. Please +1 or -1 for this proposal.

**Comment by bogdandrutu** [comment]
Ok, I see no objections. I will go ahead and change this to "oteps" ("OpenTelemetry Enhancement Proposal")

**Comment by bogdandrutu** [comment]
Done.
