### ISSUE TITLE
profiles/follow up: consistent time format

### ISSUE THREAD

**Issue by florianl** [open-telemetry/oteps#253]
This is a follow up for https://github.com/open-telemetry/oteps/pull/239#discussion_r1496080289 around the request for a consistent time precision:

In `ProfileContainer` there are `start_time_unix_nano` and `end_time_unix_nano`. Should we have the same precision with `timestamps` in `Sample` and also use `ns` instead of `ms`?

https://github.com/open-telemetry/oteps/blob/dc619dfc70f174ef31caf90f14e8b00600da4049/text/profiles/0239-profiles-data-model.md?plain=1#L553-L555

With `Profile.time_nanos` there is another timestamp in the message that uses nanosecond precision.

**Comment by arminru** [comment]
cc @open-telemetry/profiling-maintainers @open-telemetry/profiling-approvers

**Comment by mtwo** [comment]
Comment from the OTel maintainer meeting: could / should this be moved to a comment on the current [Profiling PR in the OTLP](https://github.com/open-telemetry/opentelemetry-proto/pull/534) repository?

**Comment by florianl** [comment]
This issue is linked in https://github.com/open-telemetry/opentelemetry-proto/pull/534#discussion_r1552969096. As this particular issue is relevant to the specification, I did open the issue in this repository.

**Comment by petethepig** [comment]
Addressed in https://github.com/open-telemetry/opentelemetry-proto/pull/534/commits/f5b589717f79ddb5d143c9a78976f315e637cf04

**Comment by florianl** [comment]
Closing issue as resolved with https://github.com/open-telemetry/opentelemetry-proto/commit/f5b589717f79ddb5d143c9a78976f315e637cf04.
