### ISSUE TITLE
Acceptance PRs for proposed OTEPs

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/oteps#44]
In https://github.com/open-telemetry/oteps#submitting-a-new-rfc:

> 5. A new "work-in-progress" (WIP) pull request will be created with that updates the RFC's status to approved
>    * TODO: This should probably be automated

Currently there are several OTEPs merged as proposed but without any follow-up PR:
* https://github.com/open-telemetry/oteps/blob/master/text/0004-metric-configurable-aggregation.md
* https://github.com/open-telemetry/oteps/blob/master/text/0005-global-init.md

Ideally we should also have links to any follow-up PRs in the OTEP (since there's no GitHub feature for that, it is hard to find them).

CC @jmacd

**Comment by jmacd** [comment]
Sorry!

RFC 0004 is deleted in https://github.com/open-telemetry/oteps/pull/29 -- it was discussed in the 8/21 working session and we agreed to un-propose this idea.  There were requests in favor of this discussed here, on the other hand: https://github.com/open-telemetry/opentelemetry-python/pull/87.

I will create a WIP for 0005.

**Comment by jmacd** [comment]
I suggest for now that we include the 4-digit number of the RFCs modified in any PR in this repo, to help finding outstanding PRs.

**Comment by Oberon00** [comment]
0008 has currently no PR open, but the closed #51 is only temporarily so according to the last spec meeting, so I'll close this issue.
