### ISSUE TITLE
Simply RFC process to better leverage GitHub

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/oteps#54]
Currently, the process for submitting an RFC goes through several stages: `proposed` ->  `approved` -> `implemented`. While this is logical, it means that the actual RFC review cannot occur during a PR, as the PRs are only meant to address state changes in the RFC.

However - in practice - when an RFC is proposed, all of the meaningful discussion currently occurs in the initial PR.  This has turned out to work well. Github provides a lot of tooling in the PR process to support threaded discussion, line-by-line commenting, notifications, and automatic references to other PRs and issues. 

I suggest we leverage Github PRs for our approval process:

* An RFC is `proposed` by posting it as a PR.
* An RFC is `approved` when four reviewers github-approve the PR.
* If approved, the RFC is updated to use the PR ID as the RFC ID, and then merged.
* If an RFC is rejected or withdrawn, the PR is closed. Note that these RFCs submissions are still recorded, as Github retains both the discussion and the proposal, even if the branch is later deleted.
* If an RFC discussion becomes long, and the RFC then goes through a major revision, the next version of the RFC can be posted as a new PR, which references the old PR. The old PR is then closed. This makes RFC review easier to follow and participate in.

**Comment by tigrannajaryan** [comment]
>If approved, the RFC is updated to use the PR ID as the RFC ID, and then merged.

As soon as the PR is created the ID is known and can be referenced in discussions and other documents (which is good IMO). So the author of the RFC can update the RFC immediately after creating the PR since after that the ID becomes known.

The rest sounds good to me and is a good suggestion.

**Comment by carlosalberto** [comment]
Sounds good to me as well.

**Comment by tedsuo** [comment]
@tigrannajaryan I agree, the ID can be applied immediately after posting.

**Comment by c24t** [comment]
This sounds great to me, and splitting major revisions into separate PRs ought to make everyone's lives easier.
