### ISSUE TITLE
Labels for closed + unmerged PRs

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/oteps#63]
The OTEP process defines the states `rejected` and `deferred` which lead to closing a PR without it being merged. It would be great if we had & assigned labels to closed PRs to see in which state they are.
Additionally, I guess that OTEP 0008 is in a WIP state (to be reopened after being worked on by proposer) so labeling that would be good too.

**Comment by jmacd** [comment]
Not sure if you're proposing a change. What labels do you suggest?
I intend to re-open 0008 today.

**Comment by Oberon00** [comment]
My proposed change is to assign GitHub Labels to closed PRs (so no labels in the OTEP text, just in the GitHub UI).

**Comment by Oberon00** [comment]
I still think this would be nice. Otherwise we can also remove the related sections from the OTEP process, if we don't really need this.

**Comment by trask** [comment]
Closing as part of migration to spec repo which already has labels and triage process
